YAPP-Github/24th-Web-Team-1-BE

- build.gradle.kts
- scripts/pre-commit
🎫 연관 이슈
---
resolved: #26 
💁‍♂️ PR 내용
----
-  린트 프리커밋을 저장합니다
🙏 작업
----
-  린트 프리커밋 스크립트와 테스크를 추가합니다.
🙈 PR 참고 사항
----
아래 명령어를 실행하여 pre-commit 파일을 생성할 수 있습니다.
````
./gradlew gitExecutableHooks
````
📸 스크린샷
----
🤖 테스트 체크리스트
----
> feat: 린트 프리커밋을 저장합니다

- data/db/migration/entity/V1.00.0.0__draft_table_design.sql
🎫 연관 이슈
---
resolved: #52
💁‍♂️ PR 내용
----
-  ddl문의 ; 추가
🙏 작업
----
-  ddl문의 ; 추가
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
> refactor: ddl문의 ; 추가

- api-repo/build.gradle.kts
- api/build.gradle.kts
- api/src/main/kotlin/com/few/api/config/ApiConfig.kt
- api/src/main/resources/application.yml
🎫 연관 이슈
---
resolved: #50
💁‍♂️ PR 내용
----
- api, api-repo 모듈 연결
🙏 작업
----
- api 모듈의 data-jdbc 의존성을 api 방식으로 변경
- api, api-repo 모듈 연결
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
> feat: api, api-repo 모듈 연결

- api/src/main/kotlin/com/few/api/ApiMain.kt
- api/src/test/kotlin/com/few/api/web/controller/ControllerTestSpec.kt
🎫 연관 이슈
---
resolved: #60 
💁‍♂️ PR 내용
----
- ApiMan 클래스가 api 패키지 외부에 있어 이동
🙏 작업
----
- ApiMan 클래스가 api 패키지 외부에 있어 이동
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
> refactor: ApiMan 클래스가 api 패키지 외부에 있어 이동

- api/src/main/resources/application.yml
🎫 연관 이슈
---
resolved: #99
💁‍♂️ PR 내용
----
- application.yml에 email 관련 설정 추가
🙏 작업
----
- application.yml에 email 관련 설정이 빠져서 추가하였습니다.
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
> feat: application.yml에 email 관련 설정 추가

- .github/workflows/code-ci.yml
- .github/workflows/integration-test.yml
- api/Dockerfile
- api/build.gradle.kts
- api/src/main/kotlin/com/few/api/config/ApiConfig.kt
- api/src/test/kotlin/com/few/api/web/controller/subscription/SubscriptionControllerTest.kt
- api/src/test/kotlin/com/few/api/web/controller/workbook/WorkBookControllerTest.kt
- build.gradle.kts
- resources/docker/docker-compose-api.yml
- resources/docker/scripts/api-start
🎫 연관 이슈
---
resolved: #95
💁‍♂️ PR 내용
----
-  ci 액션 구축 및 배포간 오류 수정
🙏 작업
----
- ci 액션 구축 : 버저닝이 안되는 문제가 아직... <- main 에 푸시되면 동작
- test 확인 액션 구축: 조금 오래 건린다는 문제가... <- main에 PR 하면 동작
- resource/docker에 docker-compose-api 구축 및 스크립트 작성 : 배포시 활용 위해
- @EnableMVC가 없어서 동작하지 않는 문제 해결 : 로컬에서는 동작하는데.. 아직 이유는 모르겠음
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
> #95 feat: ci 액션 구축 및 배포간 오류 수정

- batch/src/main/kotlin/com/few/batch/service/article/writer/WorkBookSubscriberWriter.kt
- batch/src/test/kotlin/com/few/batch/service/article/writer/WorkBookSubscriberWriterTestSetHelper.kt
- email/src/main/resources/templates/article.html
🎫 연관 이슈
---
resolved: #117
💁‍♂️ PR 내용
----
- 배치 Writer 리펙토링
🙏 작업
----
- progress와 day가 달라서 생기는 문제 해결
- 마지막 아티클 전송후 구독 해지 로직 추가
- 메일 전송 성공한 유저만 위의 로직 수행
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
> [Refactor/#117] 배치 Writer 리펙토링

- batch/src/main/kotlin/com/few/batch/service/article/writer/WorkBookSubscriberWriter.kt
🎫 연관 이슈
---
resolved: #151
💁‍♂️ PR 내용
----
- 배치 기록 값 수정 및 추가
🙏 작업
----
- 배치 기록 값 수정
- 기존 success에서 records로 수정, records에는 전송 대상 모두의 전송 성공 여부를 기록
- 배치 기록 값 추가
- fail을 기록할 때 예외 메시지를 함께 기록하여 어떤 이유로 실패하였는지도 기록
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
> [Refactor/#151] 배치 기록 값 수정 및 추가

- api-repo/src/main/kotlin/com/few/api/repo/dao/log/LogIfoDao.kt
- api-repo/src/main/kotlin/com/few/api/repo/dao/log/command/InsertLogCommand.kt
- api/src/main/kotlin/com/few/api/domain/log/AddApiLogUseCase.kt
- api/src/main/kotlin/com/few/api/domain/log/dto/AddApiLogUseCaseIn.kt
- api/src/main/kotlin/com/few/api/web/controller/admin/ApiLogController.kt
- api/src/main/kotlin/com/few/api/web/controller/admin/request/ApiLogRequest.kt
- api/src/test/kotlin/com/few/api/web/controller/admin/ApiLogControllerTest.kt
- data/db/migration/entity/V1.00.0.6__log_ifo_table.sql
🎫 연관 이슈
---
resolved: #149
💁‍♂️ PR 내용
----
- 로깅 API 구현
🙏 작업
----
- API 콜을 통해 로그를 저장할 수 있는 API 구현하였습니다.
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
> [Feat/#149] 로깅 API 구현

- storage/src/main/kotlin/com/few/storage/image/client/dto/ImageObjectArgs.kt
- storage/src/main/kotlin/com/few/storage/image/client/util/ImageArgsGenerator.kt
🎫 연관 이슈
---
resolved: #150
💁‍♂️ PR 내용
----
- image 저장시 contentType이 재대로 지정되지 않는 문제 해결
🙏 작업
----
- image 저장시 contentType이 재대로 지정되지 않는 문제 해결: this를 잘 못 사용하고 있었습니다..ㅠㅠ
- image 지원 타입 추가
-  "jpg", "jpeg", "png", "gif" + "svg", "webp"
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
> [Fix/#150] image 저장시 contentType이 재대로 지정되지 않는 문제 해결

- api/.gitignore
- data/.gitignore
- email/.gitignore
- storage/.gitignore
🎫 연관 이슈
---
resolved #180 
💁‍♂️ PR 내용
----
제곧내
🙏 작업
----
제곧내
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
> [Feat/#180] flyway sql 파일 gitignore 추가

- .github/workflows/wip.yml
🎫 연관 이슈
---
resolved: #192
💁‍♂️ PR 내용
----
-  wip 액션 추가
🙏 작업
----
-  wip 액션 추가
사용법 참고 : https://bitlog.tistory.com/55
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
> [#192/feat] wip 액션 추가

- .github/workflows/code-ci.yml
- .github/workflows/integration-test.yml
🎫 연관 이슈
---
resolved: #194
💁‍♂️ PR 내용
----
- 액션 Job 이름 수정
🙏 작업
----
- 액션 Job 이름 수정
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
> [#194/chore] 액션 Job 이름 수정

- build.gradle.kts
🎫 연관 이슈
---
resolved #186 
💁‍♂️ PR 내용
----
제곧내
🙏 작업
----
제곧내
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
> [Fix#186] Java 컴파일 버전 및 컨테이너 설치 버전 일치

- api-repo/src/main/kotlin/com/few/api/repo/datasource/DataSourceConfig.kt
- api-repo/src/main/resources/application-api-repo-local.yml
- api-repo/src/main/resources/application-api-repo-prd.yml
- api-repo/src/test/resources/application-test.yml
- api/src/test/resources/application-test.yml
- batch/src/test/resources/application-test.yml
🎫 연관 이슈
---
resolved #89 
💁‍♂️ PR 내용
----
제곧내
🙏 작업
----
제곧내
🙈 PR 참고 사항
----
1차 적용입니다 상황에 따라 점차 늘리던가 해야 함
📸 스크린샷
----
🤖 테스트 체크리스트
----
> [Feat/#89] hikariCP config 1차 조정

- api/build.gradle.kts
- api/src/main/kotlin/com/few/api/client/subscription/SubscriptionClient.kt
- api/src/main/kotlin/com/few/api/config/ApiThreadPoolConfig.kt
- api/src/main/kotlin/com/few/api/web/filter/MDCFilter.kt
- api/src/main/kotlin/com/few/api/web/handler/LoggingHandler.kt
- api/src/main/resources/banner.txt
- api/src/test/kotlin/com/few/api/web/controller/ControllerTestContainerInitializer.kt
- batch/src/main/kotlin/com/few/batch/log/BatchServiceLogAspect.kt
- build.gradle.kts
- buildSrc/src/main/kotlin/DependencyVersion.kt
- storage/src/main/kotlin/com/few/storage/document/client/S3DocumentStoreClient.kt
- storage/src/main/kotlin/com/few/storage/document/config/S3DocumentStoreConfig.kt
- storage/src/main/kotlin/com/few/storage/image/client/S3ImageStoreClient.kt
- storage/src/main/kotlin/com/few/storage/image/config/S3ImageStoreConfig.kt
🎫 연관 이슈
---
resolved #124 
💁‍♂️ PR 내용
----
제곧내
🙏 작업
----
제곧내
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
> [Feat/#124] kotlin-logger 적용

- email/src/main/resources/templates/article.html
🎫 연관 이슈
---
resolved: #212 
💁‍♂️ PR 내용
----
- 이메일 템플릿 잘못된 사진 교체
🙏 작업
----
- 이메일 템플릿 잘못된 사진 교체
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
> [#212/fix] 이메일 템플릿 잘못된 사진 교체

- email/src/main/resources/templates/article.html
🎫 연관 이슈
---
resolved: #218 
💁‍♂️ PR 내용
----
-  이메일 제목이 긴 경우 문제 해결한 템플릿 반영
🙏 작업
----
-  이메일 제목이 긴 경우 문제 해결한 템플릿 반영
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
> [#218/refactor] 이메일 제목이 긴 경우 문제 해결한 템플릿 반영

- api-repo/src/main/kotlin/com/few/api/repo/dao/article/ArticleViewCountDao.kt
- api/src/main/kotlin/com/few/api/domain/article/handler/ArticleViewHisAsyncHandler.kt
- api/src/main/kotlin/com/few/api/domain/article/usecase/ReadArticleUseCase.kt
🎫 연관 이슈
---
resolved #230 
💁‍♂️ PR 내용
----
제곧내
🙏 작업
----
제곧내
🙈 PR 참고 사항
----
테스트 쿼리
```SQL
SELECT * FROM ARTICLE_VIEW_COUNT ORDER BY view_count DESC LIMIT 10;
```
📸 스크린샷
----
🤖 테스트 체크리스트
----
> [Fix/#230] ArticleViewCountDao Jooq 의존성 수정

- api/src/main/kotlin/com/few/api/domain/article/handler/ArticleViewHisAsyncHandler.kt
🎫 연관 이슈
---
resolved #233 
💁‍♂️ PR 내용
----
제곧내
🙏 작업
----
아래와 같이 임시 예외를 발생시켜 롤백되고 예외를 throw할 수 있도록 수정
호출 결과 정상 롤백 확인
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
> [Fix/#233] addArticleViewHis에서 runCatching 후 예외 발생시 트랜잭션 롤백되도록 수정

- api/src/main/kotlin/com/few/api/domain/article/handler/ArticleViewHisAsyncHandler.kt
- api/src/main/kotlin/com/few/api/domain/article/usecase/ReadArticlesUseCase.kt
- api/src/main/kotlin/com/few/api/domain/article/usecase/dto/ReadArticleUseCaseOut.kt
- api/src/main/kotlin/com/few/api/domain/article/usecase/dto/ReadArticlesUseCaseIn.kt
- api/src/main/kotlin/com/few/api/domain/article/usecase/dto/ReadArticlesUseCaseOut.kt
- api/src/main/kotlin/com/few/api/web/controller/article/ArticleController.kt
- api/src/main/kotlin/com/few/api/web/controller/article/response/ReadArticleResponse.kt
- api/src/main/kotlin/com/few/api/web/controller/article/response/ReadArticlesResponse.kt
- api/src/test/kotlin/com/few/api/web/controller/article/ArticleControllerTest.kt
🎫 연관 이슈
---
resolved #250 
💁‍♂️ PR 내용
----
PR #251 revert로 인한 재 PR
🙏 작업
----
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
> [Test/#250] Article 목록조회(무한스크롤) Mock API 구현 (RE)

- api-repo/src/test/kotlin/com/few/api/repo/jooq/_SampleJooqTest.kt
- api/src/test/kotlin/com/few/api/web/controller/article/ArticleControllerTest.kt
🎫 연관 이슈
---
resolved #266 
💁‍♂️ PR 내용
----
🙏 작업
----
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
> [Test/#266] 아티클 목록 조회 컨트롤러 테스트 코드 수정

- .github/labeler.yml
- .github/workflows/ecs-cd.yml
- api/build.gradle.kts
- api/src/main/resources/logback-spring.xml
- storage/src/main/kotlin/com/few/storage/config/ClientConfig.kt
🎫 연관 이슈
---
resolved: #268 
💁‍♂️ PR 내용
----
- AWS 이전 작업
🙏 작업
----
- AWS 이전 작업
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
> [Feat/#268] AWS 이전 작업

- api/src/main/kotlin/com/few/api/security/config/WebSecurityConfig.kt
🎫 연관 이슈
---
resolved: #277 
💁‍♂️ PR 내용
----
- batch 요청이 되지 않는 문제 해결
🙏 작업
----
- 로그를 봤을 때 시큐리티 필터에 걸려서 배치 요청이 안되는 것으로 파악해서 배치 주소를 시큐리티 필터에서 제외하였습니다!
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
> fix: batch 요청이 되지 않는 문제 해결

- api/src/main/kotlin/com/few/api/domain/article/usecase/ReadArticleUseCase.kt
- api/src/main/kotlin/com/few/api/domain/article/usecase/ReadArticlesUseCase.kt
- api/src/main/kotlin/com/few/api/domain/article/usecase/dto/ReadArticleUseCaseOut.kt
- api/src/main/kotlin/com/few/api/web/controller/article/ArticleController.kt
- api/src/main/kotlin/com/few/api/web/controller/article/response/ReadArticleResponse.kt
- api/src/test/kotlin/com/few/api/web/controller/article/ArticleControllerTest.kt
🎫 연관 이슈
---
resolved #279 
💁‍♂️ PR 내용
----
제곧내
🙏 작업
----
제곧내
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
> [Fix/#279] 아티클 main image url 필드 응답 추가

- api/src/main/kotlin/com/few/api/web/support/WorkBookCategory.kt
🎫 연관 이슈
---
resolved: #295 
💁‍♂️ PR 내용
----
- 메인뷰 카테고리 한글명 수정
🙏 작업
----
- CULTURE 카테고리가 문화라고 잘못들어가 있어 교양으로 수정
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
> [#295/Chore] 메인뷰 카테고리 한글명 수정

- api/build.gradle.kts
- api/src/main/kotlin/com/few/api/domain/subscription/usecase/SubscribeWorkbookUseCase.kt
- api/src/main/kotlin/com/few/api/domain/subscription/usecase/UnsubscribeAllUseCase.kt
- api/src/main/kotlin/com/few/api/domain/subscription/usecase/UnsubscribeWorkbookUseCase.kt
- api/src/main/kotlin/com/few/api/domain/subscription/usecase/dto/SubscribeWorkbookUseCaseIn.kt
- api/src/main/kotlin/com/few/api/domain/subscription/usecase/dto/UnsubscribeAllUseCaseIn.kt
- api/src/main/kotlin/com/few/api/domain/subscription/usecase/dto/UnsubscribeWorkbookUseCaseIn.kt
- api/src/main/kotlin/com/few/api/domain/workbook/article/dto/ReadWorkBookArticleUseCaseIn.kt
- api/src/main/kotlin/com/few/api/domain/workbook/article/usecase/ReadWorkBookArticleUseCase.kt
- api/src/main/kotlin/com/few/api/security/config/WebSecurityConfig.kt
- api/src/main/kotlin/com/few/api/security/filter/exception/TokenInvalidExceptionHandlerFilter.kt
- api/src/main/kotlin/com/few/api/security/token/TokenResolver.kt
- api/src/main/kotlin/com/few/api/web/controller/article/ArticleController.kt
- api/src/main/kotlin/com/few/api/web/controller/member/MemberController.kt
- api/src/main/kotlin/com/few/api/web/controller/subscription/SubscriptionController.kt
- api/src/main/kotlin/com/few/api/web/controller/subscription/request/UnsubscribeAllRequest.kt
- api/src/main/kotlin/com/few/api/web/controller/subscription/request/UnsubscribeWorkbookRequest.kt
- api/src/main/kotlin/com/few/api/web/controller/workbook/WorkBookController.kt
- api/src/main/kotlin/com/few/api/web/controller/workbook/article/WorkBookArticleController.kt
- api/src/main/kotlin/com/few/api/web/controller/workbook/article/response/ReadWorkBookArticleResponse.kt
- api/src/test/kotlin/com/few/api/domain/subscription/usecase/SubscribeWorkbookUseCaseTest.kt
- api/src/test/kotlin/com/few/api/web/controller/TestTokenUserDetailsService.kt
- api/src/test/kotlin/com/few/api/web/controller/article/ArticleControllerTest.kt
- api/src/test/kotlin/com/few/api/web/controller/subscription/SubscriptionControllerTest.kt
- api/src/test/kotlin/com/few/api/web/controller/workbook/WorkBookControllerTest.kt
- api/src/test/kotlin/com/few/api/web/controller/workbook/article/WorkBookArticleControllerTest.kt
🎫 연관 이슈
---
resolved: #300 
💁‍♂️ PR 내용
----
- 컨트롤러에 인증 구현
🙏 작업
----
- 컨트롤러에 인증 관련 코드 추가
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
> [Refactor/#300] 컨트롤러 인증 구현

- email/src/main/resources/templates/auth.html
🎫 연관 이슈
---
resolved: #303 
💁‍♂️ PR 내용
----
- 단순 이메일 스타일 변경입니다.
🙏 작업
----
- 단순 이메일 스타일 변경입니다.
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
> [Chore/#303] 단순 이메일 스타일 변경입니다.

- api/src/main/kotlin/com/few/api/security/authentication/token/TokenUserDetailsService.kt
🎫 연관 이슈
---
resolved: #308
💁‍♂️ PR 내용
----
- 시큐리티 필터 파싱 오류 해결
🙏 작업
----
- 기존 Long 파싱이 문제를 부려서 Integer로 수정합니다.!
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
> [Fix/#308]: 시큐리티 필터 파싱 오류 해결

- api/src/main/kotlin/com/few/api/security/config/WebSecurityConfig.kt
🎫 연관 이슈
---
resolved: #317 
💁‍♂️ PR 내용
----
- 시큐리티 필터 제외 목록 점검 및 수정
🙏 작업
----
- 시큐리티 필터 제외 목록 점검 및 수정
🙈 PR 참고 사항
----
시큐리티 필터 적용 API가 가시적으로 나오지 않으니 힘드네요..ㅠ
📸 스크린샷
----
🤖 테스트 체크리스트
----
> [#317/Refactor] 시큐리티 필터 제외 목록 점검 및 수정

- infra/terraform/aws/ecs.tf
- infra/terraform/aws/ssm.tf
💁‍♂️ PR 내용
----
- mailsender java -> aws 전환 작업
🙏 작업
----
- mailsender java -> aws 전환 작업
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
> [Infra/AWS/#343] ECS, SSM 메일 관련 변수 추가

- email/src/main/kotlin/com/few/email/sender/provider/AwsSESEmailSendProvider.kt
- email/src/main/kotlin/com/few/email/sender/provider/JavaEmailSendProvider.kt
🎫 연관 이슈
---
resolved: #348 
💁‍♂️ PR 내용
----
- 프로필에 따른 메일센더 빈 미생성 문제 해결
🙏 작업
----
- 프로필에 따른 메일센더 빈 미생성 문제 해결
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
> [Fix/#348] 프로필에 따른 메일센더 빈 미생성 문제 해결

- .github/workflows/ecs-cd.yml
- .github/workflows/ecs-dev-cd.yml
- api/Dockerfile.dev.pinpoint
- api/Dockerfile.prd.pinpoint
- api/build.gradle.kts
💁‍♂️ PR 내용
----
- v24.08.22.01 배포
🙏 작업
----
- v24.08.22.01 배포
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
> [RELEASE] v24.08.22.01

- api/src/main/kotlin/com/few/api/domain/subscription/usecase/SubscribeWorkbookUseCase.kt
🎫 연관 이슈
---
resolved: #367 
💁‍♂️ PR 내용
----
- #363 머지하며 빌드가 동작하지 않는 문제 해결
🙏 작업
----
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
> [Fix/#367] #363 머지하며 빌드가 동작하지 않는 문제 해결

- email/src/main/kotlin/com/few/email/sender/EmailSender.kt
- email/src/main/kotlin/com/few/email/sender/provider/AwsSESEmailSendProvider.kt
- email/src/main/kotlin/com/few/email/sender/provider/EmailSendProvider.kt
- email/src/main/kotlin/com/few/email/sender/provider/JavaEmailSendProvider.kt
🎫 연관 이슈
---
resolved: #369 
💁‍♂️ PR 내용
----
- 이메일 발신자 설정
🙏 작업
----
🙈 PR 참고 사항
----
📸 스크린샷
----
\>> 최상단 FEW LETTER <<
사진과 같이 이메일 발신자를 설정하였습니다.
🤖 테스트 체크리스트
----
> [Refactor/#369] 이메일 발신자 설정

- data/src/main/kotlin/com/few/data/common/code/CategoryType.kt
🎫 연관 이슈
---
resolved: #375 
💁‍♂️ PR 내용
----
- 카테고리에 외국어 추가
🙏 작업
----
- 카테고리에 외국어 추가
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
> [Feat/#375] 카테고리에 외국어 추가

- api/src/main/kotlin/com/few/api/web/support/WorkBookCategory.kt
- data/src/main/kotlin/com/few/data/common/code/CategoryType.kt
🎫 연관 이슈
---
resolved: #382 
💁‍♂️ PR 내용
----
- 워크북 외국어 카테고리 추가
🙏 작업
----
- 워크북 외국어 카테고리 추가
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
> [Feat/382] 워크북 외국어 카테고리 추가

- batch/src/main/kotlin/com/few/batch/service/article/writer/service/BrowseMemberEmailService.kt
🎫 연관 이슈
---
resolved: #388 
💁‍♂️ PR 내용
----
- 이메일 전송 배치에 멤버 탈퇴 확인 조건 추가
🙏 작업
----
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
> [Refactor/#388] 이메일 전송 배치에 멤버 탈퇴 확인 조건 추가

- batch/src/main/kotlin/com/few/batch/data/common/code/BatchDayCode.kt
- batch/src/main/kotlin/com/few/batch/service/article/reader/WorkBookSubscriberReader.kt
- data/src/main/kotlin/com/few/data/common/code/DayCode.kt
🎫 연관 이슈
---
resolved: #390 
💁‍♂️ PR 내용
----
- 이메일 전송 배치 전송 설정에 따라 조회하도록 수정
🙏 작업
----
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
> [Refactor/#390] 이메일 전송 배치 전송 설정에 따라 조회하도록 수정

- api/src/main/kotlin/com/few/api/web/controller/subscription/request/UpdateSubscriptionDayRequest.kt
- api/src/test/kotlin/com/few/api/web/controller/subscription/SubscriptionControllerTest.kt
🎫 연관 이슈
---
resolved: #393 
💁‍♂️ PR 내용
----
- 구독 시간 수정 바디 파라미터 이름 수정
🙏 작업
----
- dayCode -> date
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
> [Refactor/#393] 구독 시간 수정 바디 파라미터 이름 수정

- api/src/main/kotlin/com/few/api/security/authentication/authority/AuthorityUtils.kt
- api/src/main/kotlin/com/few/api/security/authentication/token/TokenUserDetails.kt
- api/src/main/kotlin/com/few/api/security/authentication/token/TokenUserDetailsService.kt
- api/src/main/kotlin/com/few/api/web/config/WebConfig.kt
- api/src/main/kotlin/com/few/api/web/controller/article/ArticleController.kt
- api/src/main/kotlin/com/few/api/web/controller/workbook/WorkBookController.kt
- api/src/main/kotlin/com/few/api/web/controller/workbook/article/WorkBookArticleController.kt
- api/src/main/kotlin/com/few/api/web/support/method/UserArgument.kt
- api/src/main/kotlin/com/few/api/web/support/method/UserArgumentDetails.kt
- api/src/main/kotlin/com/few/api/web/support/method/UserArgumentHandlerMethodArgumentResolver.kt
🎫 연관 이슈
---
resolved: #392 
💁‍♂️ PR 내용
----
- HandlerMethodArgumentResolver 적용
🙏 작업
----
- 기존에 HttpServelt을 사용해서 하던 것 HandlerMethodArgumentResolver 적용하여 수정하였습니다.
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
> [Refactor/#392] HandlerMethodArgumentResolver 적용

- batch/src/main/kotlin/com/few/batch/service/article/reader/WorkBookSubscriberReader.kt
💁‍♂️ PR 내용
----
- v24.09.19.01 
🙏 작업
----
- v24.09.19.01 
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
> [RELEASE] v24.09.19.01 
