YAPP-Github/24th-Web-Team-1-BE

.github/workflows/terrafrom_ncp_iac.yml, infra/terraform/main.tf, infra/terraform/ncp/acg.tf, infra/terraform/ncp/db.tf, infra/terraform/ncp/lb.tf, infra/terraform/ncp/main.tf, infra/terraform/ncp/nic.tf, infra/terraform/ncp/rt.tf, infra/terraform/ncp/server.tf, infra/terraform/ncp/subnet.tf, infra/terraform/ncp/tg.tf, infra/terraform/ncp/variable.tf, infra/terraform/ncp/vpc.tf, infra/terraform/variable.tf
🎫 연관 이슈
---
resolved: #7 테라폼을 활용하여 인프라를 구성합니다.
💁‍♂️ PR 내용
----
Terraform을 활용하여 NCP 인프라를 구성하였습니다.
포크(fork)된 곳 에서의 PR은  액션이 정상적으로 동작하지 않아 다시 PR 합니다. 
🙏 작업
----
- `vpc`를 구성합니다.
- `server` 인스턴스를 구성합니다.
- `acg(aws/securitygroup)`을 구성합니다.
- `database`를 구성합니다.
- `loadbalancer`를 구성합니다.
🙈 PR 참고 사항
----
- `init script`의 경우 현재 nginx를 임의로 동작하도록 구성
- `object store`의 경우 NCP 테라폼에서 아직 지원하지 않아 직접 구성하여야 합니다.
- `database`의 경우 변경 사항이 생길 경우 수정
- `app.terraform.io`를 통해 클라우드에서 테라폼 관련 기록을 관리하고 있습니다. (프리티어가 있어 무료로 사용가능)
- 해당 클라우드를 우선 @belljun3395 것을 사용하여 추후 교체해야 함
- `NCP` 역시 @belljun3395 것을 사용하는 중 
📸 스크린샷
----
🤖 테스트 체크리스트
----
=> feat: NCP 인프라를 테라폼을 활용하여 구성합니다

.github/CODEOWNERS
🎫 연관 이슈
---
resolved: #24
💁‍♂️ PR 내용
----
- api, data, email, common CODEOWNERS 추가
🙏 작업
----
- api, data, email, common CODEOWNERS를 추가하였습니다.
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
=> feat: api, data, email, common CODEOWNERS 추가

api-repo/src/main/kotlin/com/few/api/repo/dao/subscription/SubscriptionDao.kt, api-repo/src/main/kotlin/com/few/api/repo/dao/subscription/command/UpdateDeletedAtInWorkbookSubscriptionCommand.kt, api/src/main/kotlin/com/few/api/domain/subscription/UnsubscribeWorkbookUseCase.kt, data/db/migration/entity/v1.00.0.1__add_column.sql
🎫 연관 이슈
---
resolved #85 
💁‍♂️ PR 내용
----
🙏 작업
----
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
=> [Feat/#85] 구독 취소 API 보정(unsubs_opinion 컬럼 추가)

api-repo/src/main/kotlin/com/few/api/repo/dao/article/ArticleDao.kt, api-repo/src/main/kotlin/com/few/api/repo/dao/member/MemberDao.kt, api-repo/src/main/kotlin/com/few/api/repo/dao/problem/ProblemDao.kt
🎫 연관 이슈
---
resolved: #77
💁‍♂️ PR 내용
----
- 삭제되지 않은 결과 조회를 위해 isNull 조건 추가
🙏 작업
----
- 삭제되지 않은 결과 조회를 위해 isNull 조건 추가
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
=> refactor: 삭제되지 않은 결과 조회를 위해 isNull 조건 추가

api-repo/src/main/kotlin/com/few/api/repo/dao/subscription/SubscriptionDao.kt, api-repo/src/main/kotlin/com/few/api/repo/dao/subscription/query/CountWorkbookMappedArticlesQuery.kt, api-repo/src/main/kotlin/com/few/api/repo/dao/subscription/query/CountWorkbookSubscriptionQuery.kt, api-repo/src/main/kotlin/com/few/api/repo/dao/subscription/query/SelectAllWorkbookSubscriptionStatusQueryNotConsiderDeletedAt.kt, api-repo/src/main/kotlin/com/few/api/repo/dao/subscription/record/WorkbookSubscriptionStatus.kt, api/src/main/kotlin/com/few/api/domain/subscription/usecase/SubscribeWorkbookUseCase.kt
🎫 연관 이슈
---
resolved: #120
💁‍♂️ PR 내용
----
- 구독해지 후 구독하는 경우 고려하여 구독 API 수정
🙏 작업
----
- 구독 상태를 확인한 이후 구독을 진행하도록 수정
1. 멤버의 워크북에 대한 구독 정보 조회
2. 구독에 따른 구독 정보 갱신/추가 로직 진행 (* 워크북 학습을 모두 완료한 경우 예외 발행)
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
=> [Refactor/#120] 구독해지 후 구독하는 경우 고려하여 구독 API 수정

.github/workflows/batch-cron.yml
🎫 연관 이슈
---
resolved: #146 
💁‍♂️ PR 내용
----
- batch-cron 실행 오류 수정
🙏 작업
----
- batch-cron 실행 오류 수정
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
=> [#146/ fix ] batch-cron 실행 오류 수정

api/src/main/kotlin/com/few/api/web/controller/batch/BatchController.kt, api/src/main/resources/application.yml
🎫 연관 이슈
---
resolved: #165 
💁‍♂️ PR 내용
----
-  article 배치 실행 api에 인증 추가
🙏 작업
----
-  article 배치 실행 api에 인증 추가
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
=> [#165/refactor]: article 배치 실행 api에 인증 추가

batch/src/main/kotlin/com/few/batch/data/common/code/BatchCategoryType.kt, batch/src/main/kotlin/com/few/batch/data/common/code/BatchMemberType.kt, batch/src/main/kotlin/com/few/batch/service/article/writer/WorkBookSubscriberWriter.kt, batch/src/test/kotlin/com/few/batch/service/article/writer/WorkBookSubscriberWriterTest.kt, batch/src/test/kotlin/com/few/batch/service/article/writer/WorkBookSubscriberWriterTestSetHelper.kt, data/src/main/kotlin/com/few/data/common/code/CategoryType.kt, data/src/main/kotlin/com/few/data/common/code/MemberType.kt, email/src/main/kotlin/com/few/email/sender/dto/SendMailArgs.kt, email/src/main/kotlin/com/few/email/service/article/SendArticleEmailService.kt, email/src/main/kotlin/com/few/email/service/article/dto/SendArticleEmailArgs.kt, email/src/main/resources/templates/article.html, email/src/test/kotlin/com/few/email/service/article/SendArticleEmailServiceTest.kt
🎫 연관 이슈
---
resolved: #131
💁‍♂️ PR 내용
----
- 이메일 구독 내용 채워서 구현
🙏 작업
----
- SendArticleEmailArgs 구체화
- BatchCategoryType, BatchMemberType 추가: data 의존성을 추가하는 것 보다 동일한 이넘을 만들고 javadocs로 관련 기록을 하는 것이 좋지 않을까 판다하여 추가
- 이메일 내용을 채우기 위한 조회 추가: 기존의 id로만 가지고 있던 것을 활용하여 이메일 내용에 필요한 정보 조회 추가 (CONTENT, TITLE, CATEGORY_CD, WRITER NAME, URL)
🙈 PR 참고 사항
----
- email 탬플릿 수정 사항 클라이언트에 전달 받아 추가해야함
📸 스크린샷
----
🤖 테스트 체크리스트
----
=> [Feat/#131] 이메일 구독 내용 채워서 구현

api/src/main/kotlin/com/few/api/domain/problem/usecase/BrowseProblemsUseCase.kt, api/src/main/kotlin/com/few/api/domain/problem/usecase/in/BrowseProblemsUseCaseIn.kt, api/src/main/kotlin/com/few/api/domain/problem/usecase/out/BrowseProblemsUseCaseOut.kt, api/src/main/kotlin/com/few/api/web/controller/problem/ProblemController.kt, api/src/main/kotlin/com/few/api/web/controller/problem/response/BrowseProblemsResponse.kt, api/src/test/kotlin/com/few/api/web/controller/problem/ProblemControllerTest.kt
🎫 연관 이슈
---
resolved: #155
💁‍♂️ PR 내용
----
- 아티클 아이디로 문제 조회하는 API 구현
🙏 작업
----
- 기존에 구현한 selectProblemsByArticleId를 활용하여 아티클 아이디로 문제를 조회하는 API 구현
- API URL이 적절한지 논의 필요
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
=> [Feat/#155] 아티클 아이디로 문제 조회하는 API 구현

api-repo/src/test/kotlin/com/few/api/repo/dao/member/MemberDaoTest.kt, batch/src/test/kotlin/com/few/batch/service/article/writer/WorkBookSubscriberWriterTest.kt, batch/src/test/kotlin/com/few/batch/service/article/writer/WorkBookSubscriberWriterTestSetHelper.kt
🎫 연관 이슈
---
resolved: #176
💁‍♂️ PR 내용
----
- WorkBookSubscriberWriterTest 통과하지 않는 문제 해결
- selectWriter 응답 변경에 따른 수정
🙏 작업
----
- setUp에서 테이블 초기화하는 코드 추가
- 오타 수정
- selectWriter 응답 변경에 따른 수정
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
=> [Test/#176] 통과하지 않는 테스트 해결

batch/src/main/kotlin/com/few/batch/service/article/writer/WorkBookSubscriberWriter.kt
🎫 연관 이슈
---
resolved: #190
💁‍♂️ PR 내용
----
- 마지막 학습지를 받은 구독자 기록 추가
🙏 작업
----
- 기존 구현에서는 UNSUBS_OPINION에 기록을 추가하지 않아 구분하지 못하는 문제가 있어 "recieve.all"을 추가하였습니다.
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
=> [#190/refactor] 마지막 학습지를 받은 구독자 기록 추가

api/src/main/kotlin/com/few/api/config/ApiConfig.kt, api/src/main/kotlin/com/few/api/config/ApiThreadPoolConfig.kt, api/src/main/kotlin/com/few/api/config/properties/ThreadPoolProperties.kt, api/src/main/kotlin/com/few/api/domain/subscription/event/WorkbookSubscriptionEventListener.kt, api/src/main/kotlin/com/few/api/exception/properties/NotSetPropertyException.kt, api/src/main/resources/application-client-local.yml, api/src/main/resources/application-client-prd.yml, api/src/test/resources/application-test.yml
🎫 연관 이슈
---
resolved: #173
💁‍♂️ PR 내용
----
- 디스코드 훅 비동기 처리 풀 설정
🙏 작업
----
- ThreadPoolProperties를 구현해서 application.yml에 있는 thread pool 설정을 관리합니다.
- @ConfigurationPropertiesScan 추가해서 ThreadPoolProperties를 인식할 수 있도록 합니다.
- WorkbookSubscriptionEventListener에 설정한 DISCORD_HOOK_EVENT_POOL를 할당합니다.
```
discord:
thread-pool:
core-pool-size: 5
max-pool-size: 15
queue-capacity: 30
wait-for-tasks-to-complete-on-shutdown: true
await-termination-seconds: 60
```
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
=> [Feat/#173] 디스코드 훅 비동기 처리 풀 설정

batch/src/main/kotlin/com/few/batch/service/article/dto/WorkBookSubscriberItem.kt, batch/src/main/kotlin/com/few/batch/service/article/writer/WorkBookSubscriberWriter.kt
🎫 연관 이슈
---
resolved: #199
💁‍♂️ PR 내용
----
- 이메일 전송시 중복되는 값 자료형 발견하여 수정
🙏 작업
----
- 이메일 전송시 중복되는 값 자료형 발견하여 수정 List -> Set
MemberId와 TargetWorkbookId의 자료형이 List여서 중복되는 값으로 조회하는 것을 확인했습니다.
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
=> [#199/Refactor] 이메일 전송시 중복되는 값 자료형 발견하여 수정

batch/src/main/kotlin/com/few/batch/service/article/writer/WorkBookSubscriberWriter.kt
🎫 연관 이슈
---
resolved: #198 
💁‍♂️ PR 내용
----
-  in의 잘못된 사용으로 마지막 학습지를 받지 않은 구독자들도 구독을 해지하는 문제 해결
🙏 작업
----
-  in의 잘못된 사용으로 마지막 학습지를 받지 않은 구독자들도 구독을 해지하는 문제를 발견하고 수정했습니다.
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
=> [#198/fix] in의 잘못된 사용으로 마지막 학습지를 받지 않은 구독자들도 구독을 해지하는 문제 해결

api/src/test/kotlin/com/few/api/domain/article/usecase/ReadArticleUseCaseTest.kt, api/src/test/kotlin/com/few/api/domain/problem/usecase/BrowseProblemsUseCaseTest.kt, api/src/test/kotlin/com/few/api/domain/problem/usecase/CheckProblemUseCaseTest.kt, api/src/test/kotlin/com/few/api/domain/problem/usecase/ReadProblemUseCaseTest.kt, api/src/test/kotlin/com/few/api/domain/subscription/usecase/SubscribeWorkbookUseCaseTest.kt, api/src/test/kotlin/com/few/api/domain/workbook/usecase/ReadWorkbookUseCaseTest.kt
🎫 연관 이슈
---
resolved #145 
💁‍♂️ PR 내용
----
제곧내
🙏 작업
----
제곧내
🙈 PR 참고 사항
----
- MockK 사용함
- [간단한 사용법 문서 바로가기](https://blog.kotlin-academy.com/mocking-is-not-rocket-science-expected-behavior-and-behavior-verification-3862dd0e0f03)
- UC 레벨에서 딱히 단위테스트 구현 필요성 있어보이는 부분이 `SubscribeWorkbookUseCase` 정도로 보입니다..
- kotest 기반으로 JUnit을 구동하기 위해 인텔리제이에서 kotest 플러그인 설치 필요
📸 스크린샷
----
🤖 테스트 체크리스트
----
=> [Test/#145] UseCase 단위 테스트 구현

api/src/main/kotlin/com/few/api/domain/article/usecase/ReadArticlesUseCase.kt, api/src/main/kotlin/com/few/api/domain/article/usecase/dto/ReadArticleUseCaseOut.kt, api/src/main/kotlin/com/few/api/domain/article/usecase/dto/ReadArticlesUseCaseIn.kt, api/src/main/kotlin/com/few/api/domain/article/usecase/dto/ReadArticlesUseCaseOut.kt, api/src/main/kotlin/com/few/api/web/controller/article/ArticleController.kt, api/src/main/kotlin/com/few/api/web/controller/article/response/ReadArticleResponse.kt, api/src/main/kotlin/com/few/api/web/controller/article/response/ReadArticlesResponse.kt, api/src/test/kotlin/com/few/api/web/controller/article/ArticleControllerTest.kt
🎫 연관 이슈
---
resolved #250 
💁‍♂️ PR 내용
----
- 아티클 목록 조회 [API명세](https://github.com/YAPP-Github/24th-Web-Team-1-BE/wiki/%EC%95%84%ED%8B%B0%ED%81%B4_%EB%AA%A9%EB%A1%9D_%EC%A1%B0%ED%9A%8C) Mock API 구현
- "/api/v1/articles? prevArticleId={prevArticleId}"
- `prevArticleId`: 이전 스크롤(요청)에서 읽어간 마지막 아티클 ID
🙏 작업
----
🙈 PR 참고 사항
----
- Swagger HUB를 통해 호출 가능한 Mock API 입니다
📸 스크린샷
----
🤖 테스트 체크리스트
----
=> [Test/#250] Article 목록조회(무한스크롤) Mock API 구현

api-repo/src/main/kotlin/com/few/api/repo/config/LocalCacheConfig.kt, api-repo/src/main/kotlin/com/few/api/repo/dao/member/MemberCacheManager.kt, api-repo/src/main/kotlin/com/few/api/repo/dao/member/MemberDao.kt, api-repo/src/main/kotlin/com/few/api/repo/dao/workbook/WorkBookCacheManager.kt, api-repo/src/main/kotlin/com/few/api/repo/dao/workbook/WorkbookDao.kt, api/src/main/kotlin/com/few/api/domain/article/handler/ArticleViewHisAsyncHandler.kt
🎫 연관 이슈
---
resolved: #238 
💁‍♂️ PR 내용
----
- 워크북 데이터 베이스 케시 설정
🙏 작업
----
- SELECT_WORKBOOK_RECORD_CACHE 추가
- SELECT_WRITER_CACHE 추가
- selectWorkBook 메서드 캐시 설정
- selectWriter 메서드, selectWriters 메서드 데이터 캐시 설정
- 캐싱된 데이터 활용을 위한 XXXCacheManager 구현
🙈 PR 참고 사항
----
📸 스크린샷
----
엔트리 사이즈 3으로 설정후 아이디 1 -> 2 -> 3 -> 4 -> 4 조회 결과
아티클 조회시 selectWriter 수행됨
워크북 조회시 selectWriters 수행됨
selectWriter에서 캐시 저장
selectWriters에서 캐시에 저장된 값 사용
🤖 테스트 체크리스트
----
=> [Feat/#238] 워크북 데이터 베이스 케시 설정

api-repo/src/main/kotlin/com/few/api/repo/dao/member/MemberDao.kt, api-repo/src/main/kotlin/com/few/api/repo/dao/member/query/BrowseWorkbookWritersQuery.kt, api-repo/src/main/kotlin/com/few/api/repo/dao/member/record/WriterRecordMappedWorkbook.kt, api-repo/src/main/kotlin/com/few/api/repo/dao/workbook/WorkbookDao.kt, api-repo/src/main/kotlin/com/few/api/repo/dao/workbook/query/BrowseWorkBookQueryWithSubscriptionCount.kt, api-repo/src/main/kotlin/com/few/api/repo/dao/workbook/record/SelectWorkBookRecordWithSubscriptionCount.kt, api-repo/src/test/kotlin/com/few/api/repo/explain/member/MemberDaoExplainGenerateTest.kt, api-repo/src/test/kotlin/com/few/api/repo/explain/workbook/WorkbookDaoExplainGenerateTest.kt, api/src/main/kotlin/com/few/api/domain/workbook/service/WorkbookMemberService.kt, api/src/main/kotlin/com/few/api/domain/workbook/service/dto/BrowseWorkbookWriterRecordsInDto.kt, api/src/main/kotlin/com/few/api/domain/workbook/service/dto/WriterMappedWorkbookOutDto.kt, api/src/main/kotlin/com/few/api/domain/workbook/usecase/BrowseWorkbooksUseCase.kt, api/src/main/kotlin/com/few/api/domain/workbook/usecase/dto/BrowseWorkbooksUseCaseIn.kt, api/src/main/kotlin/com/few/api/domain/workbook/usecase/dto/BrowseWorkbooksUseCaseOut.kt, api/src/main/kotlin/com/few/api/web/controller/workbook/WorkBookController.kt, api/src/test/kotlin/com/few/api/domain/workbook/usecase/BrowseWorkbooksUseCaseTest.kt, api/src/test/kotlin/com/few/api/web/controller/workbook/WorkBookControllerTest.kt
🎫 연관 이슈
---
resolved: #240
💁‍♂️ PR 내용
----
- 메인 워크북 API 구현 - 워크북 API 
🙏 작업
----
- selectWriters 구현: workbookId를 가지고 writer 정보 조회
- browseWorkBookWithSubscriptionCount 구현: workbook 정보를 구독자 정보와 함께 조회 / 정렬의 경우 (구독자수, 생성일(최근)) 순으로 구현
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
=> [Feat/#240] 메인 워크북 API 구현 - 워크북 API 

api-repo/src/main/kotlin/com/few/api/repo/dao/article/ArticleDao.kt, api-repo/src/main/kotlin/com/few/api/repo/dao/article/query/SelectArticleIdByWorkbookIdAndDayQuery.kt, api-repo/src/main/kotlin/com/few/api/repo/dao/subscription/SubscriptionDao.kt, api-repo/src/main/kotlin/com/few/api/repo/dao/subscription/query/CountAllWorkbooksSubscription.kt, api-repo/src/main/kotlin/com/few/api/repo/dao/subscription/query/SelectAllMemberWorkbookSubscriptionStatusNotConsiderDeletedAtQuery.kt, api-repo/src/main/kotlin/com/few/api/repo/dao/subscription/record/MemberWorkbookSubscriptionStatusRecord.kt, api-repo/src/test/kotlin/com/few/api/repo/explain/article/ArticleDaoExplainGenerateTest.kt, api-repo/src/test/kotlin/com/few/api/repo/explain/subscription/SubscriptionDaoExplainGenerateTest.kt, api/src/main/kotlin/com/few/api/domain/subscription/service/SubscriptionArticleService.kt, api/src/main/kotlin/com/few/api/domain/subscription/service/dto/ReadArticleIdByWorkbookIdAndDayDto.kt, api/src/main/kotlin/com/few/api/domain/subscription/usecase/BrowseSubscribeWorkbooksUseCase.kt, api/src/main/kotlin/com/few/api/domain/subscription/usecase/dto/BrowseSubscribeWorkbooksUseCaseIn.kt, api/src/main/kotlin/com/few/api/domain/subscription/usecase/dto/BrowseSubscribeWorkbooksUseCaseOut.kt, api/src/main/kotlin/com/few/api/web/controller/subscription/SubscriptionController.kt, api/src/main/kotlin/com/few/api/web/support/WorkBookStatus.kt, api/src/test/kotlin/com/few/api/domain/subscription/usecase/BrowseSubscribeWorkbooksUseCaseTest.kt, api/src/test/kotlin/com/few/api/web/controller/subscription/SubscriptionControllerTest.kt
🎫 연관 이슈
---
resolved: #241 
💁‍♂️ PR 내용
----
- 메인 워크북 API 구현 - 회원 워크북 API
🙏 작업
----
- selectAllWorkbookSubscriptionStatus 쿼리 구현:  멤버의 구독 기록이 있는 워크북을 조회합니다.
- countAllWorkbookSubscription 쿼리 구현:  워크북의 구독자를 조회합니다.
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
=> [Feat/#241] 메인 워크북 API 구현 - 회원 워크북 API

api-repo/src/main/kotlin/com/few/api/repo/dao/article/ArticleViewCountDao.kt
🎫 연관 이슈
---
resolved #281 
💁‍♂️ PR 내용
----
- DB에서 아티클 조회수 순 10개씩 조회 시, 아티클 최신순 옵션이 빠져있어 발생한 문제
- DB에선 아티클 조회수 순 10개를 뽑아온 뒤, 그 10개를 애플리케이션에서 조회수가 같은 경우 최신순으로 정렬하고 있었음
- 결국 디비 단에선 조회수가 같을 경우 아티클 최신순 조건이 발생되지 않음
🙏 작업
----
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
=> [Fix/#281] 아티클 조회수 순 정렬시 옵션 추가(article최신순)

api-repo/src/main/kotlin/com/few/api/repo/dao/article/ArticleViewCountDao.kt, api/src/main/kotlin/com/few/api/domain/article/usecase/ReadArticlesUseCase.kt, data/src/main/kotlin/com/few/data/common/code/CategoryType.kt
🎫 연관 이슈
---
resolved #283 
💁‍♂️ PR 내용
----
- as-is: DB에서 Limit 10으로 조회 후 10개가 조회되었다면 isLast = false로 응답
- 아티클이 10의 배수로 존재할 경우 문제될 수 있음: 마지막 스크롤에서 10개를 응답했지만 isLast = false로 응답됨
- to-be: DB에서 조회시 limit 11로 조회하여 조회된 개수가 11개일 경우 isLast = false, 그렇지 않을 경우 isLast = true로 응답
🙏 작업
----
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
=> [Fix/#283] 아티클 개수가 10의 배수일 경우 마지막 스크롤에서 isLast=false로 응답되는 문제 해결

api-repo/src/main/kotlin/com/few/api/repo/dao/article/ArticleViewCountDao.kt, api-repo/src/main/kotlin/com/few/api/repo/dao/article/query/SelectArticlesOrderByViewsQuery.kt, api/src/main/kotlin/com/few/api/domain/article/usecase/ReadArticlesUseCase.kt
🎫 연관 이슈
---
resolved #286 
💁‍♂️ PR 내용
----
🙏 작업
----
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
=> [Fix/#286] article 전체 카테고리 반영 SQL 수정

.gitignore, api-repo/src/main/kotlin/com/few/api/repo/dao/article/ArticleMainCardDao.kt, api-repo/src/main/kotlin/com/few/api/repo/dao/article/command/ArticleMainCardExcludeWorkbookCommand.kt, api-repo/src/main/kotlin/com/few/api/repo/dao/article/record/ArticleMainCardRecord.kt, api-repo/src/main/kotlin/com/few/api/repo/dao/article/support/ArticleMainCardMapper.kt, api-repo/src/main/kotlin/com/few/api/repo/dao/member/MemberDao.kt, api-repo/src/main/kotlin/com/few/api/repo/dao/member/record/MemberIdAndNameRecord.kt, api-repo/src/main/kotlin/com/few/api/repo/dao/member/record/MemberRecord.kt, api-repo/src/main/kotlin/com/few/api/repo/dao/member/record/WriterRecord.kt, api-repo/src/main/kotlin/com/few/api/repo/dao/member/support/WriterDescription.kt, api-repo/src/test/kotlin/com/few/api/repo/dao/member/MemberDaoTest.kt, api-repo/src/test/kotlin/com/few/api/repo/dao/member/support/CommonJsonMapperTest.kt, api-repo/src/test/kotlin/com/few/api/repo/explain/member/MemberDaoExplainGenerateTest.kt, api/src/main/kotlin/com/few/api/domain/admin/document/service/ArticleMainCardService.kt, api/src/main/kotlin/com/few/api/domain/admin/document/service/dto/InitializeArticleMainCardInDto.kt, api/src/main/kotlin/com/few/api/domain/admin/document/usecase/AddArticleUseCase.kt, api/src/main/kotlin/com/few/api/domain/article/service/ReadArticleWriterRecordService.kt, api/src/main/kotlin/com/few/api/domain/article/service/dto/ReadWriterOutDto.kt, api/src/main/kotlin/com/few/api/domain/article/usecase/ReadArticleUseCase.kt, api/src/main/kotlin/com/few/api/domain/article/usecase/ReadArticlesUseCase.kt, api/src/main/kotlin/com/few/api/domain/article/usecase/dto/ReadArticleUseCaseOut.kt, api/src/main/kotlin/com/few/api/web/controller/article/ArticleController.kt, api/src/main/kotlin/com/few/api/web/controller/article/response/ReadArticleResponse.kt, api/src/test/kotlin/com/few/api/domain/article/usecase/ReadArticleUseCaseTest.kt, api/src/test/kotlin/com/few/api/web/controller/article/ArticleControllerTest.kt
🎫 연관 이슈
---
resolved #293 
💁‍♂️ PR 내용
----
🙏 작업
----
**_NOTE - 추후 작가 추가 API 추가될 때 디폴트 이미지 넣는 코드 들어가야 합니다_**
🙈 PR 참고 사항
----
- 현재 Member, article_main_card 테이블의 description, writer_description 제이슨 컬럼에 'imageUrl' 필드를 추가해 줘야 함
```SQL
-- 보정 쿼리
WITH random_url AS (
SELECT 'https://github.com/user-attachments/assets/28df9078-488c-49d6-9375-54ce5a250742' AS value
UNION ALL
SELECT 'https://github.com/user-attachments/assets/385dcafd-6737-41d7-aaa0-9db4ea6f27ea'
UNION ALL
SELECT 'https://github.com/user-attachments/assets/209da8ff-7c78-41b7-8e3e-40a2705f714a'
)
UPDATE MEMBER
SET description = JSON_SET(description, '$.imageUrl', 
(SELECT value FROM random_url ORDER BY RAND() LIMIT 1))
where type_cd = 120;
```
```SQL
UPDATE ARTICLE_MAIN_CARD a
JOIN MEMBER m ON a.writer_id = m.id
SET …
```
=> [Feat/#293] 작가 description json 필드 추가 - imageUrl(required)

api/src/main/kotlin/com/few/api/domain/member/usecase/SaveMemberUseCase.kt, email/src/main/kotlin/com/few/email/service/member/SendAuthEmailService.kt, email/src/main/kotlin/com/few/email/service/member/dto/SendAuthEmailArgs.kt, email/src/main/resources/templates/auth.html
🎫 연관 이슈
---
resolved: #298 
💁‍♂️ PR 내용
----
- 가입/인증에 따라 다른 내용 채워서 이메일 보내도록 수정
🙏 작업
----
- 가입/인증에 따라 다른 내용 채워서 이메일 보내도록 수정
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
=> [#298/refactor]: 가입/인증에 따라 다른 내용 채워서 이메일 보내도록 수정

.github/workflows/code-ci.yml, .github/workflows/ecs-cd.yml, .github/workflows/ecs-dev-cd.yml, .github/workflows/integration-test.yml, .github/workflows/sql-explain-hook.yml, .github/workflows/validate-test.yml
🎫 연관 이슈
---
resolved: #305 
💁‍♂️ PR 내용
----
- 액션 개선 및 수정
🙏 작업
----
- gradle 캐시를 사용하도록 개선
- 액션 동작 조건 수정
🙈 PR 참고 사항
----
📸 스크린샷
----
jooqCodgenAll에 걸리던 1분이 25초로 개선된 것을 확인할 수 있습니다.
테스트 코드 동작 개선은 테스트 컨테이너를 통해 추후 개선 예정
🤖 테스트 체크리스트
----
=> [Refactor/#305] 액션 개선 및 수정

api/src/main/resources/logback-spring.xml
🎫 연관 이슈
---
resolved: #276 
💁‍♂️ PR 내용
----
- 로그 중복으로 보이는 문제 해결
🙏 작업
----
- additivity="false"로 중복 로그 제거하였습니다.
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
=> [Refactor/#276] 로그 중복으로 보이는 문제 해결

api/build.gradle.kts, api/src/main/kotlin/com/few/api/domain/admin/document/usecase/PutImageUseCase.kt, api/src/main/kotlin/com/few/api/domain/admin/document/usecase/dto/PutImageUseCaseOut.kt, api/src/main/kotlin/com/few/api/web/controller/admin/AdminController.kt, api/src/main/kotlin/com/few/api/web/controller/admin/response/ImageSourceResponse.kt, api/src/test/kotlin/com/few/api/web/controller/admin/AdminControllerTest.kt, buildSrc/src/main/kotlin/DependencyVersion.kt
🎫 연관 이슈
---
resolved: #310 
💁‍♂️ PR 내용
----
- 이미지 Webp 변환 코드 구현
🙏 작업
----
- sksamuel라는 의존성을 통해 이미지 webp 변환 구현
- webp로 변환한 파일 역시 동일한 이름 + webp 확장자로 s3 및 imageIfo에 저장합니다.
- 우선 기본 응답 url은 내려줍니다. 대신 지원하는 확장자를 응답에 추가하여주었습니다.
🙈 PR 참고 사항
----
📸 스크린샷
----
확장자만 다르게 동일한 파일이 들어가는 것 확인하였습니다.
변경된 응답 
🤖 테스트 체크리스트
----
=> [Feat/#310] 이미지 Webp 변환 코드 구현

.github/workflows/code-ci.yml, .github/workflows/ecs-cd.yml, .github/workflows/ecs-dev-cd.yml, .github/workflows/lint.yml, .github/workflows/sql-explain-hook.yml, .github/workflows/validate-test.yml, api-repo/src/test/resources/application-test.yml, api-repo/src/test/resources/docker-compose.yml, api/src/test/kotlin/com/few/api/web/controller/ControllerTestSpec.kt, api/src/test/kotlin/com/few/api/web/controller/admin/AdminControllerTest.kt, api/src/test/kotlin/com/few/api/web/controller/admin/ApiLogControllerTest.kt, api/src/test/kotlin/com/few/api/web/controller/article/ArticleControllerTest.kt, api/src/test/kotlin/com/few/api/web/controller/member/MemberControllerTest.kt, api/src/test/kotlin/com/few/api/web/controller/problem/ProblemControllerTest.kt, api/src/test/kotlin/com/few/api/web/controller/subscription/SubscriptionControllerTest.kt, api/src/test/kotlin/com/few/api/web/controller/workbook/WorkBookControllerTest.kt, api/src/test/kotlin/com/few/api/web/controller/workbook/article/WorkBookArticleControllerTest.kt, api/src/test/resources/application-test.yml, api/src/test/resources/docker-compose.yml, batch/src/test/kotlin/com/few/batch/BatchTestSpec.kt, batch/src/test/kotlin/com/few/batch/service/article/writer/WorkBookSubscriberWriterTest.kt, batch/src/test/resources/application-test.yml, batch/src/test/resources/docker-compose.yml, build.gradle.kts
🎫 연관 이슈
---
resolved: #209 
💁‍♂️ PR 내용
----
- 테스트 컨테이너 및 액션 개선
🙏 작업
----
- 모듈별 테스트 컨테이너가 한번만 동작하도록 수정
- validate-test 액션에서 각 모듈의 테스트가 병렬적으로 수행될 수 있도록 수정 -> 전체적인 액션 완료 속도에는 영향이 적지만 추후 실패한 테스트만 별도로 다시 수행 시킬 수 있다는 장점이 있습니다.
🙈 PR 참고 사항
----
📸 스크린샷
----
1m 18s -> 1m 5s
미미하지만 개선.. 하였습니다.
컨테이너가 한번만 떠야 환경을 위한 도커도 한번만 떠서 개선하였습니다.!
🤖 테스트 체크리스트
----
=> [Refactor/#209] 테스트 컨테이너 및 액션 개선

api-repo/src/main/kotlin/com/few/api/repo/dao/subscription/query/SelectAllMemberWorkbookSubscriptionStatusUnsubOpinionConditionAndNotConsiderDeletedAQuery.kt
🎫 연관 이슈
---
resolved: #333 
💁‍♂️ PR 내용
----
- main-dev 연결을 위한 이슈
🙏 작업
----
- main-dev 연결을 위한 이슈
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
=> [Fix/#333] main-dev 연결을 위한 이슈

batch/src/main/kotlin/com/few/batch/service/article/writer/WorkBookSubscriberWriter.kt, batch/src/test/kotlin/com/few/batch/service/article/writer/WorkBookSubscriberWriterTest.kt
🎫 연관 이슈
---
resolved: #338 
💁‍♂️ PR 내용
----
-  구독 학습지 마지막 아티클을 받고 progess를 증가하는 문제해결
🙏 작업
----
-  구독 학습지 마지막 아티클을 받고 progess를 증가하는 문제해결
🙈 PR 참고 사항
----
📸 스크린샷
----
이전에 종료 이후 progess를 하나더 올리는 결과
progess를 하나더 올리지 않는 결과
🤖 테스트 체크리스트
----
=> [Fix/#338] 구독 학습지 마지막 아티클을 받고 progess를 증가하는 문제해결

api-repo/src/test/kotlin/com/few/api/repo/explain/ExplainGenerator.kt, api-repo/src/test/kotlin/com/few/api/repo/explain/article/ArticleDaoExplainGenerateTest.kt, api-repo/src/test/kotlin/com/few/api/repo/explain/article/ArticleMainCardDaoExplainGenerateTest.kt, api-repo/src/test/kotlin/com/few/api/repo/explain/article/ArticleViewCountDaoExplainGenerateTest.kt, api-repo/src/test/kotlin/com/few/api/repo/explain/article/ArticleViewHisDaoExplainGenerateTest.kt, api-repo/src/test/kotlin/com/few/api/repo/explain/member/MemberDaoExplainGenerateTest.kt, api-repo/src/test/kotlin/com/few/api/repo/explain/problem/ProblemDaoExplainGenerateTest.kt, api-repo/src/test/kotlin/com/few/api/repo/explain/subscription/SubscriptionDaoExplainGenerateTest.kt, api-repo/src/test/kotlin/com/few/api/repo/explain/workbook/WorkbookDaoExplainGenerateTest.kt
🎫 연관 이슈
---
resolved: #291 
💁‍♂️ PR 내용
----
- Explain과 Explain Anaylze 쿼리 실행하도록 수정
🙏 작업
----
- Explain과 Explain Anaylze 쿼리 실행하도록 수정
🙈 PR 참고 사항
----
📸 스크린샷
----
위와 같이 Explain과 Explain Anaylze 쿼리 실행하도록 수정하였습니다.
🤖 테스트 체크리스트
----
=> [Refactor/#291] Explain과 Explain Anaylze 쿼리 실행하도록 수정

api/src/main/kotlin/com/few/api/domain/article/event/ReadArticleEventListener.kt, api/src/main/kotlin/com/few/api/domain/article/event/dto/ReadArticleEvent.kt, api/src/main/kotlin/com/few/api/domain/article/usecase/BrowseArticlesUseCase.kt, api/src/main/kotlin/com/few/api/domain/article/usecase/ReadArticleUseCase.kt, api/src/main/kotlin/com/few/api/domain/workbook/article/usecase/ReadWorkBookArticleUseCase.kt, api/src/main/kotlin/com/few/api/web/controller/article/ArticleController.kt, api/src/test/kotlin/com/few/api/domain/article/usecase/ReadArticleUseCaseTest.kt, api/src/test/kotlin/com/few/api/web/controller/ControllerTestSpec.kt, api/src/test/kotlin/com/few/api/web/controller/article/ArticleControllerTest.kt
🎫 연관 이슈
---
resolved: #358 
💁‍♂️ PR 내용
----
- 아티클 읽음 기록 이벤트 처리로 리펙토링
-  ReadArticlesUseCase -> BrowseArticlesUseCase로 컨벤션 통일
🙏 작업
----
- ReadArticleEvent 생성 및 처리
🙈 PR 참고 사항
----
📸 스크린샷
----
이벤트 리스너까지는 동기로 이후 이벤트 처리는 비동기로 처리하였는데 스레드 및 트렌잭션이 분리되어 있는 것을 확인하였습니다.
🤖 테스트 체크리스트
----
=> [Refactor/#358] 아티클 읽음 기록 이벤트 처리로 리펙토링

api/src/main/kotlin/com/few/api/config/ApiConfig.kt, api/src/main/kotlin/com/few/api/web/controller/article/response/ReadArticleResponse.kt, api/src/main/kotlin/com/few/api/web/controller/subscription/response/MainViewBrowseSubscribeWorkbooksResponse.kt, api/src/main/kotlin/com/few/api/web/controller/workbook/article/response/ReadWorkBookArticleResponse.kt, api/src/main/kotlin/com/few/api/web/controller/workbook/response/BrowseWorkBooksResponse.kt, api/src/main/kotlin/com/few/api/web/controller/workbook/response/ReadWorkBookResponse.kt
🎫 연관 이슈
---
resolved: #126 
💁‍♂️ PR 내용
----
- CreatedAt이 배열로 내려가는 문제 해결
🙏 작업
----
- @EnableWebMvc 제거: @EnableWebMvc의 자동 설정 때문에 일부 WebConfig 설정 무시되는 문제라고 하는데 추가적으로 쫌 더 알아보도록 할께요!
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
=> [Fix/#126] CreatedAt이 배열로 내려가는 문제 해결

api/src/main/kotlin/com/few/api/domain/subscription/usecase/SubscribeWorkbookUseCase.kt, api/src/main/kotlin/com/few/api/domain/subscription/usecase/model/CancelledWorkbookSubscriptionHistory.kt, api/src/main/kotlin/com/few/api/domain/subscription/usecase/model/WorkbookSubscriptionHistory.kt, api/src/main/kotlin/com/few/api/domain/subscription/usecase/model/WorkbookSubscriptionStatus.kt, api/src/test/kotlin/com/few/api/domain/subscription/usecase/model/WorkbookSubscriptionHistoryTest.kt
🎫 연관 이슈
---
resolved: #363 
💁‍♂️ PR 내용
----
- SubscribeWorkbookUseCase 모델 변환
🙏 작업
----
- SubscribeWorkbookUseCase의 로직을 모델로 변환하였습니다.
🙈 PR 참고 사항
----
📸 스크린샷
----
첫 구독
구독 중
재구독
구독 완료
🤖 테스트 체크리스트
----
=> [Refactor/#363] SubscribeWorkbookUseCase 모델 변환

api/build.gradle.kts, api/src/main/kotlin/com/few/api/config/ApiConfig.kt, api/src/main/kotlin/com/few/api/config/AsyncConfig.kt, api/src/main/kotlin/com/few/api/security/config/WebSecurityConfig.kt, api/src/main/kotlin/com/few/api/web/controller/article/response/ReadArticleResponse.kt, api/src/main/kotlin/com/few/api/web/controller/workbook/article/response/ReadWorkBookArticleResponse.kt, api/src/main/kotlin/com/few/api/web/controller/workbook/response/BrowseWorkBooksResponse.kt, api/src/main/kotlin/com/few/api/web/controller/workbook/response/ReadWorkBookResponse.kt
🎫 연관 이슈
---
resolved: #385 
💁‍♂️ PR 내용
----
- 설정 파일 정리 
🙏 작업
----
- 기존에 EnableWebMvc를 제거하면 배포시 아래와 같은 로그로 종료되는 문제가 있었습니다.
- 이슈를 봤을 때 [nested-jar-support](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.2-Release-Notes#nested-jar-support) 관련된 문제였고 bootJar 옵션에 `loaderImplementation = org.springframework.boot.loader.tools.LoaderImplementation.CLASSIC`를 추가해서 해결하였습니다.
- 그 결과 해당 이슈 때문에 제거하지 못했던 LocalDataTime의 JsonFormat을 제거하였습니다.
- 추가적으로 설정 파일 분리 및 정리도 수행하였습니다.
```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.web.servlet.HandlerMapping]: Factory method 'resourceHandlerMapping' threw exception with message: Uncaught exception during scan
--
at org.springframework.beans.factory.support.SimpleInstantiationStrategy.inst …
```
=> [Refactor/#385] 설정 파일 정리

api-repo/src/main/kotlin/com/few/api/repo/dao/subscription/SubscriptionDao.kt, api/build.gradle.kts, api/src/main/kotlin/com/few/api/config/ApiConfig.kt, api/src/main/kotlin/com/few/api/config/AspectConfig.kt, api/src/main/kotlin/com/few/api/domain/common/lock/LockAspect.kt, api/src/main/kotlin/com/few/api/domain/common/lock/LockFor.kt, api/src/main/kotlin/com/few/api/domain/common/lock/LockIdentifier.kt, api/src/main/kotlin/com/few/api/domain/subscription/usecase/SubscribeWorkbookUseCase.kt
🎫 연관 이슈
---
resolved: #384 
💁‍♂️ PR 내용
----
- 구독 중복 신청 방지
🙏 작업
----
- 구독 테이블에 유니크 조건이 제거되어 중복 구독 신청이되는 문제를 발견하였습니다.
- 네임드 락을 사용하여 해당 문제를 해결하였습니다.
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
=> [Feat/#384] 구독 중복 신청 방지 위한 락 구현

api/src/main/kotlin/com/few/api/domain/member/subscription/MemberSubscriptionService.kt, api/src/main/kotlin/com/few/api/domain/member/subscription/dto/DeleteSubscriptionDto.kt, api/src/main/kotlin/com/few/api/domain/member/usecase/DeleteMemberUseCase.kt
🎫 연관 이슈
---
resolved: #398 
💁‍♂️ PR 내용
----
- 멤버 탈퇴시 구독 정보 삭제될 수 있도록 수정
🙏 작업
----
- 멤버 탈퇴시 구독 정보 삭제될 수 있도록 수정
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
=> [Refactor/#398] 멤버 탈퇴시 구독 정보 삭제될 수 있도록 수정

api/src/main/kotlin/com/few/api/domain/member/usecase/DeleteMemberUseCase.kt
🎫 연관 이슈
---
resolved: #403 
💁‍♂️ PR 내용
----
- 멤버 탈퇴시 구독 정보 의견 기록 수정 
🙏 작업
----
- 기본값인 withdrawal 사용하도록 수정
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
=> [Fix/#403] 멤버 탈퇴시 구독 정보 의견 기록 수정 

api-repo/src/main/kotlin/com/few/api/repo/dao/subscription/SubscriptionDao.kt, api-repo/src/main/kotlin/com/few/api/repo/dao/subscription/query/SelectSubscriptionQuery.kt, api-repo/src/main/kotlin/com/few/api/repo/dao/subscription/record/SubscriptionTimeRecord.kt, api-repo/src/test/kotlin/com/few/api/repo/explain/subscription/SubscriptionDaoExplainGenerateTest.kt, api/src/main/kotlin/com/few/api/domain/common/lock/LockAspect.kt, api/src/main/kotlin/com/few/api/domain/subscription/event/WorkbookSubscriptionAfterCompletionEventListener.kt, api/src/main/kotlin/com/few/api/domain/subscription/handler/SendWorkbookArticleAsyncHandler.kt, batch/src/main/kotlin/com/few/batch/service/article/writer/WorkBookSubscriberWriter.kt, data/db/migration/entity/V1.00.0.24__add_subscription_send_at.sql
🎫 연관 이슈
---
resolved: #401 
💁‍♂️ PR 내용
----
- 하루안에 재구독시 아티클 중복 전송 및 진행률 추가되는 문제 해결
🙏 작업
----
- 전송 시간을 기록하는 컬럼 추가
- 구독 이벤트 처리 수정
- 핸들러에 트랜잭션 부여
- 동일 날짜에 재구독시 아티클 전송하지 않도록 수정
🙈 PR 참고 사항
----
📸 스크린샷
----
구독후 전송시간 기록, 진행률 업데이트 확인하였습니다.
🤖 테스트 체크리스트
----
=> [Fix/#401] 하루안에 재구독시 아티클 중복 전송 및 진행률 추가되는 문제 해결

api-repo/src/main/kotlin/com/few/api/repo/dao/subscription/SubscriptionDao.kt, api-repo/src/main/kotlin/com/few/api/repo/dao/subscription/query/SelectSubscriptionQuery.kt, api-repo/src/main/kotlin/com/few/api/repo/dao/subscription/record/SubscriptionTimeRecord.kt, api-repo/src/test/kotlin/com/few/api/repo/explain/subscription/SubscriptionDaoExplainGenerateTest.kt, api/src/main/kotlin/com/few/api/domain/common/lock/LockAspect.kt, api/src/main/kotlin/com/few/api/domain/member/usecase/DeleteMemberUseCase.kt, api/src/main/kotlin/com/few/api/domain/subscription/event/WorkbookSubscriptionAfterCompletionEventListener.kt, api/src/main/kotlin/com/few/api/domain/subscription/handler/SendWorkbookArticleAsyncHandler.kt, batch/src/main/kotlin/com/few/batch/service/article/writer/WorkBookSubscriberWriter.kt, data/db/migration/entity/V1.00.0.24__add_subscription_send_at.sql
💁‍♂️ PR 내용
----
- [RELEASE] v24.09.15.01 
🙏 작업
----
- [RELEASE] v24.09.15.01 
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
=> [RELEASE] v24.09.15.01 

batch/src/main/kotlin/com/few/batch/service/article/reader/WorkBookSubscriberReader.kt
🎫 연관 이슈
---
resolved: #406 
💁‍♂️ PR 내용
----
- 매일 받기 설정한 구독 조회되지 않는 문제 해결
🙏 작업
----
- 기존에 평일 조회 쿼리에서 평일의 조건인 `0011111`만 조건으로 설정하여 매일인 `1111111`를 조회하지 못하는 문제가 있어 `or`을 통해 해결하였습니다.
수정된 쿼리 예시입니다.
```
select `SUBSCRIPTION`.`MEMBER_ID`          as `memberId`,
`SUBSCRIPTION`.`TARGET_WORKBOOK_ID` as `targetWorkBookId`,
`SUBSCRIPTION`.`PROGRESS`           as `progress`
from `SUBSCRIPTION`
where (`SUBSCRIPTION`.`SEND_TIME` = {t '09:00:00'} and
(`SUBSCRIPTION`.`SEND_DAY` = '0011111' or `SUBSCRIPTION`.`SEND_DAY` = '1111111') and
`SUBSCRIPTION`.`TARGET_MEMBER_ID` is null and `SUBSCRIPTION`.`DELETED_AT` is null);
```
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
=> [Fix/#406] 매일 받기 설정한 구독 조회되지 않는 문제 해결

api/src/test/kotlin/com/few/api/domain/member/usecase/SaveMemberUseCaseTest.kt, email/src/main/kotlin/com/few/email/sender/EmailSender.kt, email/src/main/kotlin/com/few/email/sender/provider/ArticleAwsSESEmailSendProvider.kt, email/src/main/kotlin/com/few/email/sender/provider/AwsSESEmailSendProvider.kt, email/src/main/kotlin/com/few/email/sender/provider/EmailSendProvider.kt, email/src/main/kotlin/com/few/email/sender/provider/JavaEmailSendProvider.kt, email/src/main/kotlin/com/few/email/service/article/SendArticleEmailService.kt
🎫 연관 이슈
---
resolved: #415 
💁‍♂️ PR 내용
----
- 이메일 전송 목적에 따른 이메일 전송 프로바이더 분리 및 전송 프로바이더 설정할 수 있도록 수정 그리고 전송 이메일 식별자 추가
🙏 작업
----
- 전송 이메일 식별자 추가를 위해 이메일 전송 프로바이더 분리하였습니다
- 기본으로 설정된 이메일 전송 프로바이더 말고 전송시 프로바이더를 설정할 수 있도록 수정하였습니다.
- 전송한 이메일 식별 위한 식별자를 추가하였습니다.
🙈 PR 참고 사항
----
SES에서 제공하는 값은 고유하다고 하고
JavaMailSender의 경우에는 고유하다는 것을 보장한다는 코멘트는 없네요..
📸 스크린샷
----
JavaMailSender messageId 예
🤖 테스트 체크리스트
----
=> [Refactor/#415] 이메일 전송 목적에 따른 이메일 전송 프로바이더 분리 및 전송 프로바이더 설정할 수 있도록 수정 그리고 전송 이메일 식별자 추가

api-repo/src/main/kotlin/com/few/api/repo/dao/subscription/SubscriptionDao.kt, api-repo/src/main/kotlin/com/few/api/repo/dao/subscription/command/InsertWorkbookSubscriptionCommand.kt, api-repo/src/main/kotlin/com/few/api/repo/dao/subscription/query/SelectSubscriptionSendStatusQuery.kt, api-repo/src/main/kotlin/com/few/api/repo/dao/subscription/record/SubscriptionSendStatus.kt, api/src/main/kotlin/com/few/api/domain/subscription/usecase/SubscribeWorkbookUseCase.kt, api/src/test/kotlin/com/few/api/domain/subscription/usecase/SubscribeWorkbookUseCaseTest.kt
🎫 연관 이슈
---
resolved: #417 
💁‍♂️ PR 내용
----
- 멤버가 구독 전송 시간을 변경한 상태로 추가 구독하여도 기본 구독 전송 시간으로 생성되는 문제 해결
🙏 작업
----
[As-IS]
기존에는 멤버가 구독을 하면 기본 구독 전송 정보 (평일/8시)로 구독이 생성되었습니다.
[To-BE]
현재 구독하고 있는 학습지가 있다면 해당 학습지를 기준으로 구독이 생성될 수 있도록 수정하였습니다. 
🙈 PR 참고 사항
----
현재 구독하고 있는 학습지가 있다면 해당 학습지를 기준으로 구독이 생성되는 모습
현재 구독하고 있는 학습지가 없다면(삭제되었다면) 기본 구독 정보를 기준으로 구독이 생성되는 모습
📸 스크린샷
----
🤖 테스트 체크리스트
----
=> [Fix/#417] 멤버가 구독 전송 시간을 변경한 상태로 추가 구독하여도 기본 구독 전송 시간으로 생성되는 문제 해결

api-repo/src/main/kotlin/com/few/api/repo/dao/subscription/SubscriptionDao.kt, api-repo/src/main/kotlin/com/few/api/repo/dao/subscription/command/InsertWorkbookSubscriptionCommand.kt, api-repo/src/main/kotlin/com/few/api/repo/dao/subscription/query/SelectSubscriptionSendStatusQuery.kt, api-repo/src/main/kotlin/com/few/api/repo/dao/subscription/record/SubscriptionSendStatus.kt, api/src/main/kotlin/com/few/api/domain/subscription/usecase/SubscribeWorkbookUseCase.kt, api/src/test/kotlin/com/few/api/domain/member/usecase/SaveMemberUseCaseTest.kt, api/src/test/kotlin/com/few/api/domain/subscription/usecase/SubscribeWorkbookUseCaseTest.kt, batch/src/main/kotlin/com/few/batch/service/article/reader/WorkBookSubscriberReader.kt, email/src/main/kotlin/com/few/email/sender/EmailSender.kt, email/src/main/kotlin/com/few/email/sender/provider/ArticleAwsSESEmailSendProvider.kt, email/src/main/kotlin/com/few/email/sender/provider/AwsSESEmailSendProvider.kt, email/src/main/kotlin/com/few/email/sender/provider/EmailSendProvider.kt, email/src/main/kotlin/com/few/email/sender/provider/JavaEmailSendProvider.kt, email/src/main/kotlin/com/few/email/service/article/SendArticleEmailService.kt
💁‍♂️ PR 내용
----
- v24.09.26.01
🙏 작업
----
- v24.09.26.01
🙈 PR 참고 사항
----
📸 스크린샷
----
🤖 테스트 체크리스트
----
=> [RELEASE] v24.09.26.01
